"""
Django settings for crypto_trader project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-b8r4ptxxv=hs%h9x(jd*31-#$!%f#y+a6886)^s@9i^$y#1y+z")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third party apps
    "rest_framework",
    "corsheaders",
    "django_extensions",
    
    # Local apps
    "accounts.apps.AccountsConfig",
    "trading.apps.TradingConfig",
    "ai_engine.apps.AiEngineConfig",
    "portfolio.apps.PortfolioConfig",
    "exchanges.apps.ExchangesConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "crypto_trader.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crypto_trader.wsgi.application"


# Database - Using SQLite for Django admin and sessions (MongoEngine for app models)
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# MongoEngine Configuration
import mongoengine

# Configure MongoDB connection
MONGODB_SETTINGS = {
    'db': os.getenv("MONGO_DB_NAME", "crypto_trader"),
    'host': os.getenv("MONGO_URI", "mongodb://localhost:27017"),
    'username': os.getenv("MONGO_USERNAME", ""),
    'password': os.getenv("MONGO_PASSWORD", ""),
    'authentication_source': os.getenv("MONGO_AUTH_SOURCE", "admin"),
}

# Connect to MongoDB
if MONGODB_SETTINGS['username']:
    mongoengine.connect(**MONGODB_SETTINGS)
else:
    mongoengine.connect(
        db=MONGODB_SETTINGS['db'],
        host=MONGODB_SETTINGS['host']
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_ALL_ORIGINS = DEBUG

# Celery Configuration
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Redis Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
    }
}

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "crypto_trader": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "trading": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "ai_engine": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Trading Configuration
TRADING_CONFIG = {
    "MAX_POSITION_SIZE": float(os.getenv("MAX_POSITION_SIZE", "0.1")),  # 10% of portfolio
    "RISK_PER_TRADE": float(os.getenv("RISK_PER_TRADE", "0.02")),  # 2% risk per trade
    "MAX_DAILY_LOSS": float(os.getenv("MAX_DAILY_LOSS", "0.05")),  # 5% daily loss limit
    "STOP_LOSS_PERCENTAGE": float(os.getenv("STOP_LOSS_PERCENTAGE", "0.02")),  # 2% stop loss
    "TAKE_PROFIT_PERCENTAGE": float(os.getenv("TAKE_PROFIT_PERCENTAGE", "0.06")),  # 6% take profit
}

# Exchange API Configuration
EXCHANGE_CONFIG = {
    "DELTA_EXCHANGE": {
        "API_KEY": os.getenv("DELTA_API_KEY"),
        "API_SECRET": os.getenv("DELTA_API_SECRET"),
        "SANDBOX": os.getenv("DELTA_SANDBOX", "True").lower() == "true",
        "BASE_URL": os.getenv("DELTA_BASE_URL", "https://api.delta.exchange"),
    }
}

# AI Configuration
AI_CONFIG = {
    "DEEPSEEK": {
        "API_KEY": os.getenv("DEEPSEEK_API_KEY"),
        "MODEL": os.getenv("DEEPSEEK_MODEL", "deepseek-coder"),
        "BASE_URL": os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com"),
    },
    "PINECONE": {
        "API_KEY": os.getenv("PINECONE_API_KEY"),
        "ENVIRONMENT": os.getenv("PINECONE_ENVIRONMENT", "us-east-1-aws"),
        "INDEX_NAME": os.getenv("PINECONE_INDEX_NAME", "crypto-trading"),
    },
    "OPENAI": {
        "API_KEY": os.getenv("OPENAI_API_KEY"),
        "MODEL": os.getenv("OPENAI_MODEL", "gpt-5"),
        "BASE_URL": os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
    }
}

# Market Data Configuration
MARKET_DATA_CONFIG = {
    "UPDATE_INTERVAL": int(os.getenv("MARKET_DATA_UPDATE_INTERVAL", "60")),  # seconds
    "HISTORICAL_DATA_DAYS": int(os.getenv("HISTORICAL_DATA_DAYS", "30")),
    "INDICATORS_CONFIG": {
        "RSI_PERIOD": 14,
        "MACD_FAST": 12,
        "MACD_SLOW": 26,
        "MACD_SIGNAL": 9,
        "BOLLINGER_PERIOD": 20,
        "BOLLINGER_STD": 2,
    }
}

# Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
